@startuml

class Game {
    - levels : List<Level>
    - gameMode : GameMode
    + launchLevel(Level, Player) : void
    + endGame() : void
    + placeCheckpoint() : void
    + removeCheckpoint() : void
    - restartPosition(Checkpoint) : void
}

class Level {
    - levelId : int
    - levelName : string
    - difficulty : int [1-10]
    - map : Map
    
    + generateLevel(map) : void
}

class Player {
    + playerName : string

}
class PlayerStatistics {
    - totalJumps : int
    - totalAttempts : int
    - collectedCoins : int
    - completedLevels : int
    + displayStatistics() : void
}

class LevelStatistics {
    - totalAttempts : int
    - totalJumps : int
    + displayStatistics() : void
}

abstract Character {
    # {static} defaultSpeed : float
    # currentSpeed : float
    # moveVector : Vector2
    # gravity : float
    # isAlive : bool
    # currentPosition : Tuple
    + {abstract} onClick() : void
    ' Kill character ?? ' 
}

struct Checkpoint {
    - checkpointPosition : Tuple
}

' note right of Character : Pour l'instant, moveDirection est un bool\n 0 pour la droite et 1 pour la gauche


class Cube {
    + onClick() : void
}
class Ship {
    + onClick() : void
}
class Wave {
    - gravity = 0
    + onClick() : void
}

abstract Portal {
    - portalPosition : Tuple
}

' note top of CharacterPortal : Ce sont les portails qui vont\n modifier le type de joueur
class CharacterPortal {
    - portalType : PortalType
    + transformPlayer(Player, PortalType)
}

class GravityPortal {
    - gravityModifier : float
    + modifyGravity(gravityModifier, Player) : void
}

class SpeedPortal {
    - speedModifier : float
    + modifySpeed(speedModifier, Player) : void
}

class TeleportationPortal {
    + teleportPlayer(x, y)
}

class Obstacle {
    - obstaclePosition : Tuple
    - obstacleType : ObstacleType
}

enum PortalType {
    CubePortal
    ShipPortal
    WavePortal
}

enum ObstacleType {
    Spike
    SmallSpike
    Blade
    SawBlade
}

enum GameMode {
    Normal
    Practice
} 

Player "1" -- "1" Character :  posséder 
Player "1" -- "1" PlayerStatistics : posséder

Game "1" -- "1" Player : jouer
Game *-- Level
Game "1" o-- "0..*" Checkpoint 

Level *-- Obstacle
Level o-- Portal
Level "1" -left "1" LevelStatistics : posséder 

Character <|-- Cube
Character <|-- Ship
Character <|-- Wave

Portal <|-- CharacterPortal

Portal <|-- GravityPortal
Portal <|-- SpeedPortal
Portal <|-- TeleportationPortal

@enduml