@startuml Usecase
left to right direction
title Diagramme de cas d'utilisation - GeomeTry

actor Joueur

rectangle "Menu principal" {
    Joueur -d-> (Jouer)
    (Jouer) ..> (Choisir un niveau) : <<include>>
    Joueur --> (Quitter le jeu)
}

rectangle Partie {
    (Jouer) <.. (Mettre en pause) : <<extends>>
    (Jouer) <.. (Sauter) : <<extends>>

    rectangle Pause {
        (Mettre en pause) <.. (Reprendre la partie) : <<extends>>
    }
}

@enduml